# Generated by Django 4.1.3 on 2025-01-12 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookgenre',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookgenre',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
