# Generated by Django 4.1.3 on 2025-01-12 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksapi', '0002_rename_book_id_bookgenre_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
    ]
